### ISSUE TITLE
Unable to set Envs for browser

### ISSUE THREAD

**Issue by aleksandrov** [mxschmitt/playwright-go#104]
Hi

I'm wonder is it a bug or I'm doing something wrong? I'm trying to pass environment variable to the browser like:
```
	b, err := pw.Chromium.Launch(playwright.BrowserTypeLaunchOptions{
		Env: map[string]interface{}{
			"DISPLAY": ":99",
		},
	})
```

and getting `FATAL   Error found     {"error": "could not send message: could not send message to server: env: expected array, got object"}`

Version used: `github.com/mxschmitt/playwright-go v0.171.1` 

UPDATE: I enabled `DEBUGP=1` and got:
```
SEND>{"guid":"BrowserType@07f6a400aa7d2fba2442974fc31bc482","id":1,"method":"launch","params":{"env":{"DISPLAY":":99"}}}
RECV>{"id":1,"guid":"","method":"","params":null,"result":null,"error":{"error":{"name":"Error","message":"env: expected array, got object","stack":"Error: env: expected array, got object\n    at /snapshot/playwright-cli/node_modules/playwright/lib/protocol/validatorPrimitives.js:69:19\n    at /snapshot/playwright-cli/node_modules/playwright/lib/protocol/validatorPrimitives.js:63:16\n    at Object.BrowserTypeLaunchParams (/snapshot/playwright-cli/node_modules/playwright/lib/protocol/validatorPrimitives.js:81:27)\n    at DispatcherConnection._validateParams (/snapshot/playwright-cli/node_modules/playwright/lib/dispatchers/dispatcher.js:122:32)\n    at DispatcherConnection.dispatch (/snapshot/playwright-cli/node_modules/playwright/lib/dispatchers/dispatcher.js:146:36)\n    at Transport.onmessage (/snapshot/playwright-cli/lib/driver.js:48:61)\n    at Immediate._onImmediate (/snapshot/playwright-cli/node_modules/playwright/lib/protocol/transport.js:70:26)\n    at processImmediate (internal/timers.js:456:21)"}}}
```

**Comment by aleksandrov** [comment]
I think its a bug not version mismatch.

Playwright 1.7 validates "envs" field as an array, while we are sending the object - has https://github.com/microsoft/playwright/blob/bbb411a99c69c89f03253e3be08b767a482d3c9b/src/protocol/validator.ts#L150

**Comment by mxschmitt** [comment]
The environment variables require additional serialisation: https://github.com/microsoft/playwright-python/blob/47d42d84e307e7cdde670f8d85b3fd05bb347729/playwright/_impl/_browser_type.py#L134

You can try to pass the environment variable to the Go process as a workaround that should also work.
