### ISSUE TITLE
panic: interface conversion: interface {} is nil, not *playwright.channel

### ISSUE THREAD

**Issue by applecat** [mxschmitt/playwright-go#110]
I get panic exception instead of err if selector doesn't exist:

Every thing works fine when element exists on page (<a> tag):
```
	linkElement, err := entry.QuerySelector("a")
	if err != nil {
		log.Fatalf("could not get link element: %v", err)
	}
```

But panic raised when if dosn't (<a class="someclass"> tag):
```
	linkElement, err := entry.QuerySelector("a.someclass")
	if err != nil {
		log.Fatalf("could not get link element: %v", err)
	}
```

```panic: interface conversion: interface {} is nil, not *playwright.channel```

**Comment by mxschmitt** [comment]
@applecat 
thanks for reporting, forgot there to add a strict nil check. Created a PR with the fix!
