### ISSUE TITLE
Fix tags to work with go modules

### ISSUE THREAD

**Issue by lkraider** [mxschmitt/playwright-go#115]
Please fix the tagging in the project.

Only old tags are showing because they respect semantic versioning:

```
$ go list -m -versions github.com/mxschmitt/playwright-go
github.com/mxschmitt/playwright-go v0.171.0 v0.171.1
```

`v0.1100` should probably be set to `v0.1100.0` (I am not sure about the logic of the numbers you are using here).

**Comment by mxschmitt** [comment]
Should be fixed, sorry for the inconvenience. The reason behind the weird version number is that it should represent the upstream version in some way and still be under the 0.X version range.

I hope to find some more time in the future to move to the normal 1.X release cycle.
