### ISSUE TITLE
[Bug]: Verify Storage State handling

### ISSUE THREAD

**Issue by rusq** [mxschmitt/playwright-go#120]
Hey team,

I'm experimenting with playwright, and trying to save the authenticated state using the `context.StorageState()`
However, struggling to find the way to restore the stored state.

While investigating, found the reference in this [doc](https://playwright.dev/docs/auth/), and API doc for [NewContext](https://playwright.dev/docs/api/class-browser/#browsernewcontextoptions) says that there should be an Option that allows to restore the state, namely `storageState`.

However, browsing the sources it seems that it is not present in the [current implementation](https://github.com/mxschmitt/playwright-go/blob/067f4185d7b5d1f2fffacbc7ac2cfae47b8afe9a/generated-structs.go#L3).

My go.mod
```
// ...
github.com/mxschmitt/playwright-go v0.1100.0
// ...
```

If there's a workaround for this, I'd like to know it.  I did try saving cookies, and loading them into context, but auth says NO and requires login.

Is there a way to regenerate with this option or are there any plans on adding it? 

Thanks!

**Comment by rusq** [comment]
Also, when trying to regenerate the files, I'm struggling to find the 
`playwright/utils/doclint/generateGoApi.js`

dug through the playwright repo commits with no luck.  How does this work?

Using this dockerfile to create a build env:
```docker
FROM mcr.microsoft.com/playwright:bionic

WORKDIR /tmp
RUN curl -LO https://golang.org/dl/go1.16.3.linux-amd64.tar.gz
RUN rm -rf /usr/local/go && tar -C /usr/local -xzf go1.16.3.linux-amd64.tar.gz
RUN echo 'export PATH=/usr/local/go/bin:$PATH' >> /root/.bashrc
    

WORKDIR /build

COPY  . .
# ms/playwright is cloned in the same dir as go-playwright and moved to / during the build.
RUN mv playwright ..


ENTRYPOINT [ "/bin/bash" ]
```

Running 
```
root@abf47fdd0385:/build# ./scripts/generate-api.sh 
Generating Interfaces
Generated Interfaces
internal/modules/cjs/loader.js:883
  throw err;
  ^

Error: Cannot find module '/playwright/utils/doclint/generateGoApi.js'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:880:15)
    at Function.Module._load (internal/modules/cjs/loader.js:725:27)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:72:12)
    at internal/main/run_main_module.js:17:47 {
  code: 'MODULE_NOT_FOUND',
  requireStack: []
}
```

```
root@abf47fdd0385:/playwright# find . -iname generateGoApi.js
root@abf47fdd0385:/playwright# 
```

**Comment by rusq** [comment]
![](https://media.tenor.com/images/1fb93e098589d31f5023b7d32418f013/tenor.gif)

**Comment by mxschmitt** [comment]
Hey! The file is currently located in a fork: https://github.com/mxschmitt/playwright/tree/docs/golang-generation

I can also take a look probably tomorrow if you want. :)

**Comment by rusq** [comment]
Thanks Max, I was able to run the generate script, and as expected it did not generate the StorageStateOption (otherwise, it would already be here 28 days ago, when you bumped the version to 1.10)

This library is a good effort, thank you!
