### ISSUE TITLE
Possible to add CDPSession?

### ISSUE THREAD

**Issue by sicko7947** [mxschmitt/playwright-go#121]
In nodejs api reference cdpsession was introduced. But I couldn't find it anywere in go version. 
https://playwright.dev/docs/api/class-cdpsession

Any plans of adding this feature in the future?

**Comment by mxschmitt** [comment]
no concrete plans yet but should be easily to add. Will probably add it then hopefully soon when I've got some time.

**Comment by mxschmitt** [comment]
It was added in #128
