### ISSUE TITLE
Feature request: add support for aws lambda functions / google functions

### ISSUE THREAD

**Issue by annymosse** [mxschmitt/playwright-go#126]
add support for aws lambda functions or google functions or MS functions for chromium or firefox ,and native drivers using go instead node (versions which is downloaded each time when executing the function so it will consume more resources and time).

**Comment by mxschmitt** [comment]
Closing in favour of https://github.com/microsoft/playwright/issues/2404

**Comment by noperator** [comment]
Heads up that the Playwright team [recently closed](https://github.com/microsoft/playwright/issues/2404#issuecomment-1003635338) the referenced issue above "to manage expectations."

For the record, I've been able to successfully run Playwright for Go in Lambda via an Amazon Linux 2 container image. I can provide more details here if that'd be helpful to you, @annymosse.

**Comment by annymosse** [comment]
@noperator thank you, This will be useful for me and others.
