### ISSUE TITLE
[question] detect if a window alert is opened

### ISSUE THREAD

**Issue by x0rzkov** [mxschmitt/playwright-go#132]
Hi @mxschmitt ,

Hope you are all well !

Thanks for this amazing work with playwright-go :-)

I am working on a xss/sqli crawler and I was wondering if it is possible to catch a window alert triggered with playwright ?

Thanks for any insights or inputs on that question.

Cheers,
X.

**Comment by mxschmitt** [comment]
Sorry for the late reply, yes it is possible, you can listen for dialogs and dismiss them e.g. See here for example code:

https://github.com/mxschmitt/playwright-go/blob/7430509759138a5186c0ecdbb0da5e15cf071949/tests/dialog_test.go

Keep in mind, that an alert in the web-world is blocking, so it need to get dismissed.
