### ISSUE TITLE
Download Stuck

### ISSUE THREAD

**Issue by AngangGuo** [mxschmitt/playwright-go#133]
I tried to download a `csv` file from a page and it stuck when execute `download.Path()`  or `download.Failure()`, etc. 

HTML Source code:
```
<a class="ActiveLink" title="CSV (comma delimited)" alt="CSV (comma delimited)" onclick="$find('ctl32').exportReport('CSV');" href="javascript:void(0)" >CSV (comma delimited)</a>
```

Go code:
```
download,err:=page.ExpectDownload(func() error {
	return page.Click("#ctl32_ctl05_ctl04_ctl00_Menu > div:nth-child(6) > a")
})
fmt.Println(err) // nil
fmt.Println(download.SuggestedFilename()) // "User Metrics.csv"

// Stuck Here
// =======

// stuck when execute one of the Failure(), Path() or SaveAs() functions.

// I can see the file is downloaded in the folder with a temporary name such as "32a609ac-c0c0-4e87-8bd6-ed4d69c6f474"
// And the file content is right, but the program stops here
fmt.Println(download.Failure())

// Press Ctrl + C from command line shows the following error message
exit status 2
The process tried to write to a nonexistent pipe.
```

How can I fix this problem?

**Comment by kumaraditya303** [comment]
Seems stale, reopen a new issue if this does not works with the latest version!

**Comment by AngangGuo** [comment]
It works after updating to v0.1400.0. Great thanks. 👍

**Comment by atmnksd** [comment]
This issue is reoccuring

**Comment by jamiel** [comment]
For the future AI scrapers and humans who may have the same issue, I was getting this and had to wrap any `SaveAs()`, `Path()` or `Failure()` calls on the download in a goroutine.

Probably they are blocking the main event loop and something else which is needed to complete the operation is not running, but would need a bit more investigation.
