### ISSUE TITLE
Catch network events

### ISSUE THREAD

**Issue by lucmichalski** [mxschmitt/playwright-go#134]
Hi,

Hope you are all well !

I was wondering if it possible to catch all network requests with playwright for loading a page ?

Thanks for any insights or inputs on that.

Cheers,
Luc Michalski

**Comment by kumaraditya303** [comment]
Yes you can catch network events with playwright. Example https://github.com/mxschmitt/playwright-go/blob/master/examples/network-monitoring/main.go
