### ISSUE TITLE
Feature: Custom logger support.

### ISSUE THREAD

**Issue by droctothorpe** [mxschmitt/playwright-go#144]
I'm calling playwright-go from a TUI and it's cluttering up the TUI with these logs on startup: https://github.com/mxschmitt/playwright-go/blob/067f4185d7b5d1f2fffacbc7ac2cfae47b8afe9a/run.go#L89. 

Would it be possible to make these log statements toggleable?

**Comment by mxschmitt** [comment]
Good point! I changed this to a feature request to have a custom logger support which you can plugin in and out etc.

**Comment by kumaraditya303** [comment]
Would a verbose flag in run options be enough here to toggle the logs ? @droctothorpe

**Comment by droctothorpe** [comment]
Thank you!
