### ISSUE TITLE
Feature Request: Make downloading some components optional when calling 'playwright.Run()'.

### ISSUE THREAD

**Issue by supercom32** [mxschmitt/playwright-go#151]
It would be nice if when calling 'playwright.Run()' if some of the components could be made optional to download. For example,
rather than automatically downloading Firefox, Chromium, and ffmpeg, maybe give the user an option to download only those which are required for their project? In addition, it might also be nice if the user has more control over how this download occurs. Perhaps maybe adding a method to check if a download is nessisary without the need to call 'playwright.Run()' first? Or a method to handle the download yourself manually, or surpress the downloader progress bars generated for each component that is being downloaded?

**Comment by mxschmitt** [comment]
When calling playwright.Run you can specify already a few things, see here. Does this fit for your use-case? 

https://github.com/mxschmitt/playwright-go/blob/067f4185d7b5d1f2fffacbc7ac2cfae47b8afe9a/run.go#L199-L203

**Comment by supercom32** [comment]
Hi,

Ah, I didn't realize this. For the most part, this does solve much of the problem. I will consider the matter resolved! Thanks again!
