### ISSUE TITLE
Request: The ability to locate psudo-elements or obtain a refreshed copy of the DOM once psudo elements are loaded in.

### ISSUE THREAD

**Issue by supercom32** [mxschmitt/playwright-go#153]
Recently I noted an increasing amount of websites which have started to use psudo-elements (for example, "::before" and "::after")  to insert large amounts of dynamic content on a page. While opening your browsers debug console, your free to locate these elements using standard methods (like xPath) which appears to work just fine. However when using playwright-go, this does not work since psudo elements do not yet exist in the DOM (from playwrights perspective), and are only added in after the fact.

Is there a proper way for playwright-go to locate psudo elements using standard methods like xPath? Or, is there a way to somehow ask playwright-go to refresh it's copy of the DOM once a page has been fully loaded (when the DOM is finally updated to what the user actually sees? Ie. HTML [→ JavaScript] → CSS → Result)?

This is rather an important issue, since you cannot interact with any portion of a page that is contained under a psudo-element, and large portions (if not entire chunks) of pages are now using them for displaying dynamic content?

**Comment by mxschmitt** [comment]
I would recommend asking this question in the Playwright issue tracker on: https://github.com/microsoft/playwright/issues/new/choose

Since Playwright for Go uses most of that logic and is just a wrapper around it. Thanks!
