### ISSUE TITLE
[internal]: fix that there is XML in the doc comments

### ISSUE THREAD

**Issue by mxschmitt** [mxschmitt/playwright-go#159]
- [ ] fix that there is XML in the doc comments -> it should not be there (was not correct since a few months)
- [x] fix that there are csharp examples in the generated_interfaces.go
- [x] Re-introduce EmulateMedia

**Comment by kumaraditya303** [comment]
@mxschmitt What XML should be removed, `<summary/>` from structs ?

**Comment by mxschmitt** [comment]
> @mxschmitt What XML should be removed, `<summary/>` from structs ?

https://github.com/mxschmitt/playwright-go/blob/master/generated-structs.go

The .NET comment generator should be removed since we want just the text.

**Comment by kumaraditya303** [comment]
We don't even want cref tags ?

**Comment by mxschmitt** [comment]
> We don't even want cref tags ?

I don't think that's a thing in the Go world, but feel free to verify.

https://blog.golang.org/godoc

**Comment by mxschmitt** [comment]
Fixed in #173
