### ISSUE TITLE
Supplied Args in BrowserTypeLaunchOptions are not overriding.

### ISSUE THREAD

**Issue by RichDavis1** [mxschmitt/playwright-go#162]
I'm providing a specific set of flags, namely trying to get the headless browser to utilize GPU and specify webgl_vendor and none of them seem to be working. Everytime I launch the browser, my webgl_vendor gets set to "Google Inc.~Google SwiftShader".

Would appreciate any guidance if I'm potentially handling this wrong or if there's a potential bug.

Here's my launch config.

```
	return pw.Chromium.Launch(playwright.BrowserTypeLaunchOptions{
		Headless:       playwright.Bool(true),
		Proxy:          &proxy,
		ExecutablePath: &chromePath,
		Channel:       playwright.BrowserChannelChrome,
		Args: []string{
			"--gpu-vendor-id",
			"--enable-webgl-image-chromium",
			"--enable-webgl2-compute-context",
		},
	})
```

**Comment by kumaraditya303** [comment]
Closing since it is stale and needs more info
