### ISSUE TITLE
Change array of structs to a single pointer to struct in options 

### ISSUE THREAD

**Issue by kumaraditya303** [mxschmitt/playwright-go#174]
Change `options ...TracingStopOptions` to `options  *TracingStopOptions`

**Comment by mxschmitt** [comment]
First feedback which I received was that spreading it is a better developer experience on the customer side but "harder" to implement on our side. Maybe we clean it internally up to have less if len(options) == 1 checks everywhere. He preferred the spreading variant.

**Comment by kumaraditya303** [comment]
@mxschmitt Afaik array spread is used to take varargs in python terms, I don't think it is a better experience on customer side either because they can only provide one options as we explicitly check for `len(options) == 1` and if they accidently provide more than `1` then there won't be a compiler error because it accepts varargs and it will not works as expected. If we change it to a single pointer to struct then it will be better on both the customer side and on the implementation side.

**Comment by kumaraditya303** [comment]
There are some inconsistencies in the API currently see https://github.com/mxschmitt/playwright-go/blob/5589ab4ea13a89f36465a0dac4a9ddf4824994f7/page.go#L463 as it should be `options ...SomeOptions`

**Comment by kumaraditya303** [comment]
Until golang supports default args for parameters, passing for now
