### ISSUE TITLE
A way to listen for events like console logs

### ISSUE THREAD

**Issue by j-fuentes** [mxschmitt/playwright-go#186]
I was trying to read console logs in a page but I couldn't figure out how to do it.

With [JS Playwright apparently you can define a listener for `"console"` events](JS Playwright apparently you can define a listener for `"console"` events):

```
page.on('console', async msg => {
  for (let i = 0; i < msg.args().length; ++i)
    console.log(`${i}: ${await msg.args()[i].jsonValue()}`);
});
await page.evaluate(() => console.log('hello', 5, {foo: 'bar'}));
```

From what I can see in playwright-go documentation, this is not possible.

Am I missing something or it is just a missing feature?

**Comment by mxschmitt** [comment]
It is possible, see the following test (use On instead of Once): https://github.com/mxschmitt/playwright-go/blob/067f4185d7b5d1f2fffacbc7ac2cfae47b8afe9a/tests/console_message_test.go#L10-L33

**Comment by j-fuentes** [comment]
Oh, I see!

I missed the `EventEmitter` interface and that I could use that with `Page`.

Many thanks for the quick answer.
