### ISSUE TITLE
Remove RunOptions and install driver with cli

### ISSUE THREAD

**Issue by kumaraditya303** [mxschmitt/playwright-go#200]
Currently the users install the browsers with the library but with this they need to install all the browser moreover then don't know the other features of the cli, so we should remove the old apis and only keep cli to install browsers/ deps etc 

cc @mxschmitt

**Comment by mxschmitt** [comment]
I would include both ways, the difference is that in Go you ship binaries and don't usually have an interpreter on your production system / container anymore.

So maybe a docs section which includes your CLI mode, refers to the upstream CLI documentation and the way via the API would help.

**Comment by mxschmitt** [comment]
e.g.

```
go run github.com/mxschmitt/playwright-go/cmd/playwright install-deps
# Or
go install github.com/mxschmitt/playwright-go/cmd/playwright
playwright --help
```

**Comment by kumaraditya303** [comment]
Fixed in install guide
