### ISSUE TITLE
SetExtraHTTPHeaders causing CORS errors

### ISSUE THREAD

**Issue by KiqoCode** [mxschmitt/playwright-go#201]
Hi,

When trying to set some extra security headers through Playwright we get some CORS errors which makes the site unusable. 
It works fine when doing it manually in chrome through a chrome extension to add HTTP Headers. 
However, one extension is also causing this CORS error, but in that extension you also have to specify a URL for that HTTP Header, the extension that actually works in Chrome you don't specify any url. So my guess in that somewhere in Playwright Go it's using a URL for that header.. (Only a guess though)

We are adding it like:

```
header := make(map[string]string)
header["x-bypass-recaptcha-v3"] = "secret"

context, err := browser.NewContext(playwright.BrowserNewContextOptions{ExtraHttpHeaders: header})
```

**Comment by kumaraditya303** [comment]
Closing there is no reproducer or dom
