### ISSUE TITLE
Docker zombie process playwright.sh

### ISSUE THREAD

**Issue by KiqoCode** [mxschmitt/playwright-go#209]
Hi,

I'm running playwright-go in a docker container and have an issue with zombie processes of playwright.sh.
After adding 'dumb-init' we stopped getting the chromium zombie processes but still see 'playwright,sh' as new zombie process after each scheduled run. 
We are closing playwright with both browser.close() and playwright.close() after each run.

```
root     123405  0.0  0.0      0     0 ?        Z    11:58   0:00 [playwright.sh] <defunct>
root     123424  0.0  0.0      0     0 ?        Z    11:58   0:00 [playwright.sh] <defunct>
root     128870  0.0  0.0      0     0 ?        Z    12:08   0:00 [playwright.sh] <defunct>
root     128884  0.0  0.0      0     0 ?        Z    12:08   0:00 [playwright.sh] <defunct>
```

Any ideas?

**Comment by mxschmitt** [comment]
Which version are are you using?

**Comment by KiqoCode** [comment]
@mxschmitt 0.14

**Comment by kumaraditya303** [comment]
@KiqoCode There is no `playwright.close` available only `playwright.stop` which works just fine
