### ISSUE TITLE
Proxy use example?

### ISSUE THREAD

**Issue by delamae** [mxschmitt/playwright-go#239]
My attempt:
```go
browser, err := pw.Chromium.Launch(playwright.BrowserTypeLaunchOptions{
	Headless: playwright.Bool(true),
	Proxy: playwright.BrowserTypeLaunchOptionsProxy{
		Server:   playwright.String("localhost:8080"),
		Username: playwright.String("jeff"),
		Password: playwright.String("12345"),
	},
})
```
Visual Studio Code compiler complains:

> cannot use (playwright.BrowserTypeLaunchOptionsProxy literal) (value of type playwright-go.BrowserTypeLaunchOptionsProxy) as *playwright-go.BrowserTypeLaunchOptionsProxy value in struct literal

An example of proxy use or a correction to my example would be appreciated.

**Comment by kumaraditya303** [comment]
@delamae You need to pass it as a pointer see :

```go
browser, err := pw.Chromium.Launch(playwright.BrowserTypeLaunchOptions{
		Proxy: &playwright.BrowserTypeLaunchOptionsProxy{
			Server:   playwright.String("localhost:8080"),
			Username: playwright.String("jeff"),
			Password: playwright.String("12345"),
		},
	})
```

**Comment by delamae** [comment]
My man. Fixing the code with a single character. Thank you
