### ISSUE TITLE
Add missing functionality/methods

### ISSUE THREAD

**Issue by mxschmitt** [mxschmitt/playwright-go#34]
Current report (`node scripts/validate-interfaces.js`):

Missing API interface functions:
- [x] BrowserContext.SetHTTPCredentials
- [x] BrowserContext.StorageState
- [x] ElementHandle.WaitForElementState
- [x] ElementHandle.WaitForSelector

**Comment by tutturen** [comment]
Hi Max,

Great project you have here, I like it a lot. I want to use this in one of my projects, but the pages contain a lot of dropdowns, which I don't know how to handle at the moment without `Page.selectOption`. Is implementing `Page.selectOption` currently on your roadmap? If not, can you point me in the right direction for me to implement it?

**Comment by mxschmitt** [comment]
Hi, if you want feel free to add it yourself as Pull Request, as a reference it might just need a 1:1 wrapper from [Playwright for Python](https://github.com/microsoft/playwright-python/blob/de5f967f040883e48aa545c7f70a8b8ce7e83207/playwright/frame.py#L422) and some tests. If you don't feel comfortable, then I can also implement it, probably during end of the week.

**Comment by tutturen** [comment]
Thanks! I will take a stab at if I get the time before the weekend.

**Comment by tutturen** [comment]
I just wanted to inform you that I did not find the time to fix the issue. Sorry about that.

**Comment by mxschmitt** [comment]
@tutturen FYI a few weeks ago SelectOption was added by @lcmtwn 🚀

**Comment by tutturen** [comment]
That is nice! Thanks for letting me know!
