### ISSUE TITLE
feat: add BrowserType.connect()

### ISSUE THREAD

**Issue by vania-pooh** [mxschmitt/playwright-go#37]
We are delivering Moon - a solution for running parallel Selenium and Playwright tests. The only prerequisite to use it is being able to connect directly to Playwright websocket. https://aerokube.com/moon/latest/#_using_playwright Is it possible to do this right now?

**Comment by mxschmitt** [comment]
Hi, the driver implementations can't connect yet to them. But we'll add this in a few weeks (blocked upstream).

Related to https://github.com/microsoft/playwright-python/issues/183.

**Comment by vania-pooh** [comment]
@mxschmitt ok, this is known to work in original Node.js implementation.

**Comment by mxschmitt** [comment]
Added in https://github.com/mxschmitt/playwright-go/pull/163

**Comment by troyk** [comment]
@mxschmitt is there an example available that allows the equivalent to the below code we are using in the js playwright lib?

```javascript
  const browser = await chromium.connectOverCDP({
      endpointURL: "http://localhost:9222"
  });  
```
