### ISSUE TITLE
Is posible to attach a new page to an existing wb?

### ISSUE THREAD

**Issue by davixcky** [mxschmitt/playwright-go#47]
Hi,

I'm working with this library and the only thing that I can say is, GREAT JOB!!

I want to replicate the next diagram. Imagine that you have the same app A and B, but A is a daemon (service) and B is the interface. What I want to do is avoid to open the browser every time the user need to do something, I just want to have loaded the broswer and then just go to page that the user is requesting. That is possible?
![image](https://user-images.githubusercontent.com/34346877/93657031-83651e00-f9f4-11ea-9f3f-4d1d6710e6e0.png)

Thanks in advance.

**Comment by mxschmitt** [comment]
Hi, probably [BrowserType.connect()](https://playwright.dev/#version=v1.4.1&path=docs%2Fapi.md&q=browsertypelaunchserveroptions) is what you want. So you can launch a browser server and then share the websocket URL. This can be used to connect to the browser server.

But unfortunately its currently not yet possible, see #37 for more details.

**Comment by davixcky** [comment]
Hi,

Thanks for answering. I made a mistake with my logic, so I decided to implement  a different model for resolve the problem.

Thanks
