### ISSUE TITLE
Using Plain Go Type

### ISSUE THREAD

**Issue by AngangGuo** [mxschmitt/playwright-go#49]
From [example](https://github.com/mxschmitt/playwright-go/blob/master/examples/download/main.go):
```
browser, err := pw.Chromium.Launch(playwright.BrowserTypeLaunchOptions{
    Headless: playwright.Bool(false),
})
```
Is it possible to use plain Go type bool like:
```
browser, err := pw.Chromium.Launch(playwright.BrowserTypeLaunchOptions{
    Headless: false,
})
```
You can convert `false` to `playwright.Bool(false)` in `Launch()` method.

This will be easier for end user. 
Also the you may not need to export `Bool()` or similar type convert method as a public method.

**Comment by mxschmitt** [comment]
Hi,

yeah, the point of that is it's otherwise not possible to differentiate if a value was set or not internally. GRPC/Protobuf are using it in the same way.
(These methods are basically returning it's pointer value)

**Comment by AngangGuo** [comment]
Understand. Thanks.

**Comment by AngangGuo** [comment]
Go Nuts Mailing List:
https://groups.google.com/u/1/g/golang-nuts/c/ucgTYyBe0es
