### ISSUE TITLE
Install only one browser?

### ISSUE THREAD

**Issue by adeptedcase** [mxschmitt/playwright-go#52]
Is is possible to install only one browser using the playwright-driver? I don't need all three downloaded.

Thanks

**Comment by mxschmitt** [comment]
Hi, not yet, we rely for that on an upstream issue: https://github.com/microsoft/playwright/issues/3866

**Comment by adeptedcase** [comment]
Hi, that's great, thank you

**Comment by mxschmitt** [comment]
@adeptedcase out of curiosity, what is your use case for Playwright for Go? Would help us to understand for building features etc.

**Comment by adeptedcase** [comment]
@mxschmitt I've emailed you to explain what I'm doing

**Comment by mxschmitt** [comment]
Status: Upstream API is now there, CLI arguments needs to be forwarded.

**Comment by noperator** [comment]
Is there a way to entirely avoid installing any browsers at all? I'm specifying my own via `ExecutablePath`. More info on my use case (and workaround) [here](https://github.com/noperator/spindrift#troubleshooting).

**Comment by mxschmitt** [comment]
@noperator not yet but let me implement something and then you can review the API.

**Comment by mxschmitt** [comment]
@noperator I've created a PR #113. Let me know if you have suggestions there, thanks!
