### ISSUE TITLE
Waiting for one of the selectors or alert windows

### ISSUE THREAD

**Issue by AngangGuo** [mxschmitt/playwright-go#53]
I want to use this library to automate my daily tasks, like giving a job id, go to a page find all the pallets of this job and process these pallets one by one. Or giving an asset id, I verify if all the processing data are valid for this asset, etc.

When I click a button, it may show out different content, or alert messages according to the data.
What's the proper way in playwright-go to process these situation?

What's the correct way to do this in playwright-go?
```
    await page.goto(loadLink)

    // if load id is valid, this PALLET DETAILS table will show out
    const hdTable = "#ctl00_ctl00_LoadPallet"
    // if load id is invalid, it will show warning window with this close button
    const closeButton = "#ctl00_ctl00_LoadGridClose"
    await Promise.race([
        page.click(closeButton).then(() => false),
        page.waitForSelector(hdTable).then(() => true)
    ]).then(value => {
        if (!value) {
            console.log("wrong load id: ", loadID)
            return
        }
    })
```
Thanks

**Comment by mxschmitt** [comment]
Hi sorry for the late response, maybe using time.After in combination with a switch to have similar Promise.race behaviour could work.

For automating daily tasks I would probably use JavaScript since in Go its kinda abstract.

**Comment by AngangGuo** [comment]
Thanks for the advise.
