### ISSUE TITLE
Page on response event: Response.Body() not working

### ISSUE THREAD

**Issue by rad1k4l** [mxschmitt/playwright-go#55]
my code: 

    `account.Pages.Active().On("response", func(response *playwright.Response) {
		if strings.Index(response.URL(), "authenticationstate") != -1 {
			out.Debug("Response detected", response.URL())
			accountAuthStatus := authState{}

			out.Debug("decoding json")
			jsonDecodeError := response.JSON(&accountAuthStatus)

			if jsonDecodeError != nil {
				out.Debug("Error decode", jsonDecodeError.Error())
			}
			out.Debug("printing result")
			out.Debug(accountAuthStatus.String())
		}
	})`

response.JSON() freezes the code and not returns any value ,

**Comment by mxschmitt** [comment]
Weird, is it a big response? Because the normal test passes for it. I updated the internal upstream Playwright library, maybe it works now better.

**Comment by mxschmitt** [comment]
Closed because of inactivity, feel free to reopen if it's still persistent.
