### ISSUE TITLE
Missing types for page error events.

### ISSUE THREAD

**Issue by StarpTech** [mxschmitt/playwright-go#65]
Hi, I can't see the type definition of the [page errors](https://playwright.dev/docs/verification?_highlight=event#page-errors).
For example:

```go
page, _ := browserContext.NewPage()
page.Once("pageerror", func(err ???) {
	c.Logger().Errorf("an error on the page was detected: %s", err)
})
```
I also recommend using custom function types e.g

```go
type RequestFailedEventHandler = func(request *Request)
```

**Comment by mxschmitt** [comment]
Hi, great suggestion but hard to implement on my side probably. We would need like in TypeScript the option to overload methods or use type maps based on the first argument e.g. which is not available in Go.

**Comment by mxschmitt** [comment]
Providing types in Go is afaik not possible for such cases except we create wrapper functions for all of the events which we could do. Let me know if I'm wrong. Also added support for pageError in the PR #82.

**Comment by StarpTech** [comment]
Correct me, if I'm wrong but every playwright driver consumes JSON from stdout. This JSON represents a specific event with a fixed data shape. Based on the message "type" shouldn't it be possible to parse them as go structs? Then we would need to develop against specific cases to reach type safety.

https://github.com/mxschmitt/playwright-go/blob/90056e2984ad0b64d55a1f54c1de2e64c06f5b2e/transport.go#L44
https://github.com/mxschmitt/playwright-go/blob/90056e2984ad0b64d55a1f54c1de2e64c06f5b2e/transport.go#L63

**Comment by StarpTech** [comment]
This is essentially what the C# driver does.

- https://github.com/microsoft/playwright-sharp/blob/ac2cc6e95e9a81c918366fa38877e3e7b0aa8682/src/PlaywrightSharp/Transport/Channels/PageChannel.cs#L96
- https://github.com/microsoft/playwright-sharp/blob/6b4454035620c5fec7f4ff5e8b78775231deea85/src/PlaywrightSharp/Transport/Connection.cs#L325

They serialize the data based on the `method` name.

**Comment by mxschmitt** [comment]
Yes its communicating over stdin/stdout with JSON and the payload length prefixed. We already parse them as go structs, internally for some purposes, like `pageerror` it internally gets converted into a playwright.Error type struct, for worker, its a Worker instance, for request/response its such a object, it depends on the kind of event which type it is in the end.

I don't get the original question maybe, this is now possible:

```go
page.Once("pageerror", func(err playwright.Error) {
	c.Logger().Errorf("an error on the page was detected: %v", err)
})
```

Does this answer your question?

**Comment by StarpTech** [comment]
This issue was only about page error events. Your example would fix it. :+1: 

In general, I think the driver overuse reflection and empty interface. In many cases, we could develop against concrete types.

- https://github.com/mxschmitt/playwright-go/blob/5b4ed0ebc859c8c86596e9b0760d6ae3946c136d/helpers.go#L301-L326
- https://github.com/mxschmitt/playwright-go/blob/5b4ed0ebc859c8c86596e9b0760d6ae3946c136d/expect_wrapper.go#L7-L23

I like this approach https://mionskowski.pl/generic-event-dispatcher-in-go to handle events from different types.

**Comment by mxschmitt** [comment]
Cool, thanks for confirming. Some events like that or others are missing, try to come up with them over the next week.

Yeah I didn't do much Go for a while and thought its fine to solve it like that. I wanted to keep the API pretty much the same as we have upstream so it corresponds with Python, Java or C#. If you have concrete improvements, I would be happy if you want to collaborate with me on the codebase, waitForEvent/newExpectWrapper is definitely something which is improvable. 👍
