### ISSUE TITLE
Interface vs Struct

### ISSUE THREAD

**Issue by AngangGuo** [mxschmitt/playwright-go#80]
Thanks for this great library and your hardwork to make it great.

From https://pkg.go.dev/github.com/mxschmitt/playwright-go#pkg-index, the methods show out if the type is struct(like `Playwright`):
```
type Playwright
    func Run(options ...*RunOptions) (*Playwright, error)
    func (c *Playwright) Dispose()
    func (p *Playwright) Stop() error
```

But No method shows out if the type is defined as interface(like `Page`), we need to go to the type definition to find the available methods.
```
type Page
```

Is it possible to define the `Page` as struct?
```
type Page struct {
    // non export fields
}

func (*Page) Click(selector string, options ...PageClickOptions) error
func (*Page) Fill(selector, text string, options ...FrameFillOptions) error
... ...
```
What do you think about it?
Thanks.

**Comment by mxschmitt** [comment]
Hi,
what is the reason, that you want to navigate to the underlying implementation? Probably to improve the documentation on go pkg?

The main reason why I did it like that was because I generate the interfaces to ensure I implement all the Playwright methods. I generate it basically out of the upstream API.

In Visual Studio Code e.g. it seems to work fine with auto completion etc.

I'm definitely open for feedback since this library is quite new, so I really appreciate it!

**Comment by AngangGuo** [comment]
Yes, the type struct + methods definitely improves the documentation on  https://pkg.go.dev. For example, you can find all the available methods for http.Request are listed under type Request in https://pkg.go.dev/net/http.

Also Go's interface type tends to be small and for other types to implement them, like Stringer, Reader, Writer, etc. Maybe I'm wrong but I don't see any type implement `Page` interface or `Frame` interface.

**Comment by mxschmitt** [comment]
The main reasons why I choose interfaces was:
- I can easily generate them and add documentation - as I do right now
- I can ensure that I implement all upstream functions - the compiler ensures it

The downside of it is that:

- We don't have a super rich documentation on go pkg side
- The users are not able to navigate directory from the IDE the internal implementation (need to go over the implementors). But I think thats fine and not important.

I get your point, that interfaces should be small but also think that in this case the arguments for an interface outweigh.

**Comment by AngangGuo** [comment]
Thanks, maybe add detailed documents in the website later on.

**Comment by ysmood** [comment]
@mxschmitt @AngangGuo I think use struct is better for both user and maintainer.

> I can easily generate them and add documentation - as I do right now

Actually, you can also generate code for structs, I don't understand why the only interface can do that.

> I can ensure that I implement all upstream functions - the compiler ensures it

You can check this during the CI process, pretty easy to use reflect to list all the methods of a struct.

I suggest checking the code design of [Rod](https://github.com/go-rod/rod/), it may help.
